### ISSUE TITLE
ERROR IN V1.1.0

### ISSUE THREAD

**Issue by aireet** [mitchellh/protoc-gen-go-json#14]
when i update v1.1.0 

i got this 

`
protoc-gen-go-json: parse error
--go-json_out: protoc-gen-go-json: Plugin failed with status code 1.
make: *** [gen-grpc] Error 1
`

**Comment by simonxmh** [comment]
This was causing issues for me as well. It was the latest change in the repo https://github.com/mitchellh/protoc-gen-go-json/pull/9

You need to change existing flags to a boolean:
for example.
       --go-json_out=enums_as_ints=true,emit_defaults=true:/out-dir

**Comment by mitchellh** [comment]
Yes sorry, this was a breaking change (unexpected) from updating to the latest Go proto libraries. The README is up to date.
