### ISSUE TITLE
Support EmitDefaultValues

### ISSUE THREAD

**Issue by awltr** [mitchellh/protoc-gen-go-json#19]
Currently the option `emit_defaults` maps to `EmitUnpopulated`. But there is a new option `EmitDefaultValues`, see [protojson#MarshalOptions](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions)

Any chance to add this? I would suggest option `emit_defaults_without_null` or similar

**Comment by mfridman** [comment]
If you file an issue over at https://github.com/mfridman/protoc-gen-go-json, I can go ahead and implement that.

_I believe_ Mitchell wants to eventually archive this repository (see [Planned Repo Archive](https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc)) and I'd be happy to continue supporting said Protobuf plugin.
